/**
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2022 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

#ifndef REG_MAP_H
#define REG_MAP_H

#define ctrl_reg_base 0x6800

#define ISPU_GLB_CALL_EN  (ctrl_reg_base + 0x00)
#define ISPU_CONFIG       (ctrl_reg_base + 0x02)
#define ISPU_STATUS       (ctrl_reg_base + 0x04)
#define ISPU_IF2S_FLAG    (ctrl_reg_base + 0x0C)
#define ISPU_S2IF_FLAG    (ctrl_reg_base + 0x0E)
#define ISPU_DOUT_00      (ctrl_reg_base + 0x10)
#define ISPU_DOUT_00_B    (ctrl_reg_base + 0x11)
#define ISPU_DOUT_01      (ctrl_reg_base + 0x12)
#define ISPU_DOUT_01_B    (ctrl_reg_base + 0x13)
#define ISPU_DOUT_02      (ctrl_reg_base + 0x14)
#define ISPU_DOUT_02_B    (ctrl_reg_base + 0x15)
#define ISPU_DOUT_03      (ctrl_reg_base + 0x16)
#define ISPU_DOUT_03_B    (ctrl_reg_base + 0x17)
#define ISPU_DOUT_04      (ctrl_reg_base + 0x18)
#define ISPU_DOUT_04_B    (ctrl_reg_base + 0x19)
#define ISPU_DOUT_05      (ctrl_reg_base + 0x1A)
#define ISPU_DOUT_05_B    (ctrl_reg_base + 0x1B)
#define ISPU_DOUT_06      (ctrl_reg_base + 0x1C)
#define ISPU_DOUT_06_B    (ctrl_reg_base + 0x1D)
#define ISPU_DOUT_07      (ctrl_reg_base + 0x1E)
#define ISPU_DOUT_07_B    (ctrl_reg_base + 0x1F)
#define ISPU_DOUT_08      (ctrl_reg_base + 0x20)
#define ISPU_DOUT_08_B    (ctrl_reg_base + 0x21)
#define ISPU_DOUT_09      (ctrl_reg_base + 0x22)
#define ISPU_DOUT_09_B    (ctrl_reg_base + 0x23)
#define ISPU_DOUT_10      (ctrl_reg_base + 0x24)
#define ISPU_DOUT_10_B    (ctrl_reg_base + 0x25)
#define ISPU_DOUT_11      (ctrl_reg_base + 0x26)
#define ISPU_DOUT_11_B    (ctrl_reg_base + 0x27)
#define ISPU_DOUT_12      (ctrl_reg_base + 0x28)
#define ISPU_DOUT_12_B    (ctrl_reg_base + 0x29)
#define ISPU_DOUT_13      (ctrl_reg_base + 0x2A)
#define ISPU_DOUT_13_B    (ctrl_reg_base + 0x2B)
#define ISPU_DOUT_14      (ctrl_reg_base + 0x2C)
#define ISPU_DOUT_14_B    (ctrl_reg_base + 0x2D)
#define ISPU_DOUT_15      (ctrl_reg_base + 0x2E)
#define ISPU_DOUT_15_B    (ctrl_reg_base + 0x2F)
#define ISPU_DOUT_16      (ctrl_reg_base + 0x30)
#define ISPU_DOUT_16_B    (ctrl_reg_base + 0x31)
#define ISPU_DOUT_17      (ctrl_reg_base + 0x32)
#define ISPU_DOUT_17_B    (ctrl_reg_base + 0x33)
#define ISPU_DOUT_18      (ctrl_reg_base + 0x34)
#define ISPU_DOUT_18_B    (ctrl_reg_base + 0x35)
#define ISPU_DOUT_19      (ctrl_reg_base + 0x36)
#define ISPU_DOUT_19_B    (ctrl_reg_base + 0x37)
#define ISPU_DOUT_20      (ctrl_reg_base + 0x38)
#define ISPU_DOUT_20_B    (ctrl_reg_base + 0x39)
#define ISPU_DOUT_21      (ctrl_reg_base + 0x3A)
#define ISPU_DOUT_21_B    (ctrl_reg_base + 0x3B)
#define ISPU_DOUT_22      (ctrl_reg_base + 0x3C)
#define ISPU_DOUT_22_B    (ctrl_reg_base + 0x3D)
#define ISPU_DOUT_23      (ctrl_reg_base + 0x3E)
#define ISPU_DOUT_23_B    (ctrl_reg_base + 0x3F)
#define ISPU_DOUT_24      (ctrl_reg_base + 0x40)
#define ISPU_DOUT_24_B    (ctrl_reg_base + 0x41)
#define ISPU_DOUT_25      (ctrl_reg_base + 0x42)
#define ISPU_DOUT_25_B    (ctrl_reg_base + 0x43)
#define ISPU_DOUT_26      (ctrl_reg_base + 0x44)
#define ISPU_DOUT_26_B    (ctrl_reg_base + 0x45)
#define ISPU_DOUT_27      (ctrl_reg_base + 0x46)
#define ISPU_DOUT_27_B    (ctrl_reg_base + 0x47)
#define ISPU_DOUT_28      (ctrl_reg_base + 0x48)
#define ISPU_DOUT_28_B    (ctrl_reg_base + 0x49)
#define ISPU_DOUT_29      (ctrl_reg_base + 0x4A)
#define ISPU_DOUT_29_B    (ctrl_reg_base + 0x4B)
#define ISPU_DOUT_30      (ctrl_reg_base + 0x4C)
#define ISPU_DOUT_30_B    (ctrl_reg_base + 0x4D)
#define ISPU_DOUT_31      (ctrl_reg_base + 0x4E)
#define ISPU_DOUT_31_B    (ctrl_reg_base + 0x4F)
#define ISPU_INT1_CTRL    (ctrl_reg_base + 0x50)
#define ISPU_INT1_CTRL_B  (ctrl_reg_base + 0x51)
#define ISPU_INT1_CTRL_C  (ctrl_reg_base + 0x52)
#define ISPU_INT1_CTRL_D  (ctrl_reg_base + 0x53)
#define ISPU_INT2_CTRL    (ctrl_reg_base + 0x54)
#define ISPU_INT2_CTRL_B  (ctrl_reg_base + 0x55)
#define ISPU_INT2_CTRL_C  (ctrl_reg_base + 0x56)
#define ISPU_INT2_CTRL_D  (ctrl_reg_base + 0x57)
#define ISPU_INT_STATUS   (ctrl_reg_base + 0x58)
#define ISPU_INT_STATUS_B (ctrl_reg_base + 0x59)
#define ISPU_INT_STATUS_C (ctrl_reg_base + 0x5A)
#define ISPU_INT_STATUS_D (ctrl_reg_base + 0x5B)
#define ISPU_INT_PIN      (ctrl_reg_base + 0x5C)
#define ISPU_ALGO         (ctrl_reg_base + 0x70)
#define ISPU_ALGO_B       (ctrl_reg_base + 0x71)
#define ISPU_ALGO_C       (ctrl_reg_base + 0x72)
#define ISPU_ALGO_D       (ctrl_reg_base + 0x73)
#define ISPU_ARAW_X       (ctrl_reg_base + 0x80)
#define ISPU_ARAW_X_B     (ctrl_reg_base + 0x81)
#define ISPU_ARAW_X_C     (ctrl_reg_base + 0x82)
#define ISPU_ARAW_X_D     (ctrl_reg_base + 0x83)
#define ISPU_ARAW_Y       (ctrl_reg_base + 0x84)
#define ISPU_ARAW_Y_B     (ctrl_reg_base + 0x85)
#define ISPU_ARAW_Y_C     (ctrl_reg_base + 0x86)
#define ISPU_ARAW_Y_D     (ctrl_reg_base + 0x87)
#define ISPU_ARAW_Z       (ctrl_reg_base + 0x88)
#define ISPU_ARAW_Z_B     (ctrl_reg_base + 0x89)
#define ISPU_ARAW_Z_C     (ctrl_reg_base + 0x8A)
#define ISPU_ARAW_Z_D     (ctrl_reg_base + 0x8B)
#define ISPU_GRAW_X       (ctrl_reg_base + 0x8C)
#define ISPU_GRAW_X_B     (ctrl_reg_base + 0x8D)
#define ISPU_GRAW_X_C     (ctrl_reg_base + 0x8E)
#define ISPU_GRAW_X_D     (ctrl_reg_base + 0x8F)
#define ISPU_GRAW_Y       (ctrl_reg_base + 0x90)
#define ISPU_GRAW_Y_B     (ctrl_reg_base + 0x91)
#define ISPU_GRAW_Y_C     (ctrl_reg_base + 0x92)
#define ISPU_GRAW_Y_D     (ctrl_reg_base + 0x93)
#define ISPU_GRAW_Z       (ctrl_reg_base + 0x94)
#define ISPU_GRAW_Z_B     (ctrl_reg_base + 0x95)
#define ISPU_GRAW_Z_C     (ctrl_reg_base + 0x96)
#define ISPU_GRAW_Z_D     (ctrl_reg_base + 0x97)
#define ISPU_ERAW_0       (ctrl_reg_base + 0x98)
#define ISPU_ERAW_0_B     (ctrl_reg_base + 0x99)
#define ISPU_ERAW_0_C     (ctrl_reg_base + 0x9A)
#define ISPU_ERAW_0_D     (ctrl_reg_base + 0x9B)
#define ISPU_ERAW_1       (ctrl_reg_base + 0x9C)
#define ISPU_ERAW_1_B     (ctrl_reg_base + 0x9D)
#define ISPU_ERAW_1_C     (ctrl_reg_base + 0x9E)
#define ISPU_ERAW_1_D     (ctrl_reg_base + 0x9F)
#define ISPU_ERAW_2       (ctrl_reg_base + 0xA0)
#define ISPU_ERAW_2_B     (ctrl_reg_base + 0xA1)
#define ISPU_ERAW_2_C     (ctrl_reg_base + 0xA2)
#define ISPU_ERAW_2_D     (ctrl_reg_base + 0xA3)
#define ISPU_TEMP         (ctrl_reg_base + 0xA4)
#define ISPU_TEMP_B       (ctrl_reg_base + 0xA5)
#define ISPU_TEMP_C       (ctrl_reg_base + 0xA6)
#define ISPU_TEMP_D       (ctrl_reg_base + 0xA7)
#define ISPU_CALL_EN      (ctrl_reg_base + 0xB8)
#define ISPU_CALL_EN_B    (ctrl_reg_base + 0xB9)
#define ISPU_CALL_EN_C    (ctrl_reg_base + 0xBA)
#define ISPU_CALL_EN_D    (ctrl_reg_base + 0xBB)

#define ctrl_reg_ext 0x6900

#define TIMESTAMP0        (ctrl_reg_ext + 0x40)
#define TIMESTAMP2        (ctrl_reg_ext + 0x42)
#define ISPU_DTIME_0      (ctrl_reg_ext + 0x48)
#define ISPU_DTIME_1      (ctrl_reg_ext + 0x4A)
#define ISPU_DUMMY_CFG_1  (ctrl_reg_ext + 0x74)
#define ISPU_DUMMY_CFG_2  (ctrl_reg_ext + 0x76)
#define ISPU_DUMMY_CFG_3  (ctrl_reg_ext + 0x78)
#define ISPU_DUMMY_CFG_4  (ctrl_reg_ext + 0x7A)

#endif

